// Shared icon — renders the Lucide asset (Assets.xcassets/Icons) for a given
// SF-Symbol name, so iOS draws the SAME glyph as the Compose app (pixel-identical
// cross-platform icons). Template-rendered, so it tints with the inherited
// foreground color — set `.foregroundStyle(...)` on the call site as usual.
//
// Usage: `MadarIcon("cart", size: IconSize.md).foregroundStyle(theme.colors.accent)`
// The name catalog (madarIconAsset) is generated by tool/gen-icons.sh.
import SwiftUI

struct MadarIcon: View {
    @Environment(\.layoutDirection) private var layoutDirection
    let name: String
    var size: CGFloat = IconSize.md

    init(_ name: String, size: CGFloat = IconSize.md) {
        self.name = name
        self.size = size
    }

    /// Directional glyphs flip in RTL so chevrons/back-arrows point the right way.
    static let mirror: [String: String] = [
        "chevron.right": "chevron.left", "chevron.left": "chevron.right",
        "chevron.forward": "chevron.backward", "chevron.backward": "chevron.forward",
    ]

    private var resolved: String {
        layoutDirection == .rightToLeft ? (Self.mirror[name] ?? name) : name
    }

    var body: some View {
        Image(madarIconAsset[resolved] ?? resolved)
            .renderingMode(.template)
            .resizable()
            .interpolation(.high)
            .scaledToFit()
            .frame(width: size, height: size)
    }
}
