// GENERATED by tool/gen-icons.sh — do not edit.
package app.madar.ui

import org.jetbrains.compose.resources.DrawableResource
import app.madar.resources.Res
import app.madar.resources.ic_arrow_down_left
import app.madar.resources.ic_arrow_up_down
import app.madar.resources.ic_arrow_up_right
import app.madar.resources.ic_badge_check
import app.madar.resources.ic_banknote
import app.madar.resources.ic_bike
import app.madar.resources.ic_building_2
import app.madar.resources.ic_calculator
import app.madar.resources.ic_check
import app.madar.resources.ic_chevron_down
import app.madar.resources.ic_chevron_left
import app.madar.resources.ic_chevron_right
import app.madar.resources.ic_chevron_up
import app.madar.resources.ic_circle
import app.madar.resources.ic_circle_alert
import app.madar.resources.ic_circle_arrow_down
import app.madar.resources.ic_circle_arrow_right
import app.madar.resources.ic_circle_arrow_up
import app.madar.resources.ic_circle_check
import app.madar.resources.ic_circle_check_big
import app.madar.resources.ic_circle_dot
import app.madar.resources.ic_circle_play
import app.madar.resources.ic_circle_user
import app.madar.resources.ic_circle_x
import app.madar.resources.ic_clock
import app.madar.resources.ic_cloud_check
import app.madar.resources.ic_cloud_upload
import app.madar.resources.ic_coffee
import app.madar.resources.ic_columns_2
import app.madar.resources.ic_credit_card
import app.madar.resources.ic_croissant
import app.madar.resources.ic_cup_soda
import app.madar.resources.ic_delete
import app.madar.resources.ic_download
import app.madar.resources.ic_ellipsis
import app.madar.resources.ic_file_text
import app.madar.resources.ic_gift
import app.madar.resources.ic_glass_water
import app.madar.resources.ic_grid_2x2
import app.madar.resources.ic_hand
import app.madar.resources.ic_hash
import app.madar.resources.ic_heart
import app.madar.resources.ic_history
import app.madar.resources.ic_ice_cream_cone
import app.madar.resources.ic_inbox
import app.madar.resources.ic_landmark
import app.madar.resources.ic_layers
import app.madar.resources.ic_leaf
import app.madar.resources.ic_link
import app.madar.resources.ic_list
import app.madar.resources.ic_list_filter
import app.madar.resources.ic_lock
import app.madar.resources.ic_lock_open
import app.madar.resources.ic_log_out
import app.madar.resources.ic_mail
import app.madar.resources.ic_menu
import app.madar.resources.ic_message_square
import app.madar.resources.ic_message_square_warning
import app.madar.resources.ic_minus
import app.madar.resources.ic_package
import app.madar.resources.ic_pie_chart
import app.madar.resources.ic_plus
import app.madar.resources.ic_printer
import app.madar.resources.ic_qr_code
import app.madar.resources.ic_receipt
import app.madar.resources.ic_refresh_cw
import app.madar.resources.ic_rotate_cw
import app.madar.resources.ic_sandwich
import app.madar.resources.ic_search
import app.madar.resources.ic_settings
import app.madar.resources.ic_shopping_bag
import app.madar.resources.ic_shopping_cart
import app.madar.resources.ic_sliders_horizontal
import app.madar.resources.ic_smartphone
import app.madar.resources.ic_snowflake
import app.madar.resources.ic_star
import app.madar.resources.ic_store
import app.madar.resources.ic_tag
import app.madar.resources.ic_trash_2
import app.madar.resources.ic_triangle_alert
import app.madar.resources.ic_user
import app.madar.resources.ic_utensils_crossed
import app.madar.resources.ic_wallet
import app.madar.resources.ic_wifi
import app.madar.resources.ic_wifi_off
import app.madar.resources.ic_x

/** SF-Symbol name -> shared Lucide drawable. null = unmapped (caller draws nothing). */
fun lucideRes(sf: String): DrawableResource? = when (sf) {
    "exclamationmark.circle" -> Res.drawable.ic_circle_alert
    "exclamationmark.triangle" -> Res.drawable.ic_triangle_alert
    "exclamationmark.bubble" -> Res.drawable.ic_message_square_warning
    "xmark" -> Res.drawable.ic_x
    "xmark.circle" -> Res.drawable.ic_circle_x
    "xmark.circle.fill" -> Res.drawable.ic_circle_x
    "printer" -> Res.drawable.ic_printer
    "number" -> Res.drawable.ic_hash
    "tag" -> Res.drawable.ic_tag
    "tag.fill" -> Res.drawable.ic_tag
    "chevron.backward" -> Res.drawable.ic_chevron_left
    "chevron.left" -> Res.drawable.ic_chevron_left
    "chevron.forward" -> Res.drawable.ic_chevron_right
    "chevron.right" -> Res.drawable.ic_chevron_right
    "chevron.down" -> Res.drawable.ic_chevron_down
    "chevron.up" -> Res.drawable.ic_chevron_up
    "checkmark.circle" -> Res.drawable.ic_circle_check
    "checkmark.circle.fill" -> Res.drawable.ic_circle_check_big
    "checkmark" -> Res.drawable.ic_check
    "checkmark.seal" -> Res.drawable.ic_badge_check
    "trash" -> Res.drawable.ic_trash_2
    "trash.fill" -> Res.drawable.ic_trash_2
    "text.bubble" -> Res.drawable.ic_message_square
    "note.text" -> Res.drawable.ic_file_text
    "doc.text" -> Res.drawable.ic_file_text
    "person" -> Res.drawable.ic_user
    "person.fill" -> Res.drawable.ic_user
    "person.crop.circle.badge.clock" -> Res.drawable.ic_circle_user
    "magnifyingglass" -> Res.drawable.ic_search
    "list.bullet.rectangle" -> Res.drawable.ic_list
    "list.bullet" -> Res.drawable.ic_list
    "building.2" -> Res.drawable.ic_building_2
    "plus" -> Res.drawable.ic_plus
    "minus" -> Res.drawable.ic_minus
    "plus.forwardslash.minus" -> Res.drawable.ic_calculator
    "lock" -> Res.drawable.ic_lock
    "lock.circle" -> Res.drawable.ic_lock
    "lock.open" -> Res.drawable.ic_lock_open
    "clock.arrow.circlepath" -> Res.drawable.ic_history
    "clock" -> Res.drawable.ic_clock
    "clock.badge.checkmark" -> Res.drawable.ic_clock
    "clock.badge.exclamationmark" -> Res.drawable.ic_clock
    "tray.full" -> Res.drawable.ic_inbox
    "tray" -> Res.drawable.ic_inbox
    "tray.and.arrow.down" -> Res.drawable.ic_download
    "rectangle.portrait.and.arrow.right" -> Res.drawable.ic_log_out
    "icloud.and.arrow.up" -> Res.drawable.ic_cloud_upload
    "gearshape" -> Res.drawable.ic_settings
    "bicycle" -> Res.drawable.ic_bike
    "banknote" -> Res.drawable.ic_banknote
    "wifi.slash" -> Res.drawable.ic_wifi_off
    "wifi" -> Res.drawable.ic_wifi
    "storefront" -> Res.drawable.ic_store
    "square.stack.3d.up.fill" -> Res.drawable.ic_layers
    "square.grid.2x2.fill" -> Res.drawable.ic_grid_2x2
    "heart.circle" -> Res.drawable.ic_heart
    "hand.raised" -> Res.drawable.ic_hand
    "envelope" -> Res.drawable.ic_mail
    "ellipsis.circle" -> Res.drawable.ic_ellipsis
    "ellipsis" -> Res.drawable.ic_ellipsis
    "delete.left" -> Res.drawable.ic_delete
    "creditcard" -> Res.drawable.ic_credit_card
    "cart" -> Res.drawable.ic_shopping_cart
    "bag.fill" -> Res.drawable.ic_shopping_bag
    "arrow.triangle.2.circlepath" -> Res.drawable.ic_refresh_cw
    "arrow.right.circle" -> Res.drawable.ic_circle_arrow_right
    "arrow.clockwise" -> Res.drawable.ic_rotate_cw
    "arrow.up" -> Res.drawable.ic_chevron_up
    "arrow.down" -> Res.drawable.ic_chevron_down
    "wallet" -> Res.drawable.ic_wallet
    "bank" -> Res.drawable.ic_landmark
    "building.columns" -> Res.drawable.ic_landmark
    "qrcode" -> Res.drawable.ic_qr_code
    "qr" -> Res.drawable.ic_qr_code
    "play.circle" -> Res.drawable.ic_circle_play
    "gift" -> Res.drawable.ic_gift
    "fork.knife" -> Res.drawable.ic_utensils_crossed
    "cup.and.saucer" -> Res.drawable.ic_coffee
    "croissant" -> Res.drawable.ic_croissant
    "arrow.up.arrow.down" -> Res.drawable.ic_arrow_up_down
    "arrow.down.left" -> Res.drawable.ic_arrow_down_left
    "arrow.up.right" -> Res.drawable.ic_arrow_up_right
    "iphone" -> Res.drawable.ic_smartphone
    "line.3.horizontal" -> Res.drawable.ic_menu
    "square.grid.2x2" -> Res.drawable.ic_grid_2x2
    "circle" -> Res.drawable.ic_circle
    "largecircle.fill.circle" -> Res.drawable.ic_circle_dot
    "rectangle.split.2x1" -> Res.drawable.ic_columns_2
    "exclamationmark.triangle.fill" -> Res.drawable.ic_triangle_alert
    "cat.coffee" -> Res.drawable.ic_coffee
    "cat.mocha" -> Res.drawable.ic_coffee
    "cat.tea" -> Res.drawable.ic_coffee
    "cat.bakery" -> Res.drawable.ic_croissant
    "cat.lunch" -> Res.drawable.ic_sandwich
    "cat.icecream" -> Res.drawable.ic_ice_cream_cone
    "cat.drink" -> Res.drawable.ic_cup_soda
    "cat.water" -> Res.drawable.ic_glass_water
    "cat.ice" -> Res.drawable.ic_snowflake
    "cat.matcha" -> Res.drawable.ic_leaf
    "chart.pie" -> Res.drawable.ic_pie_chart
    "receipt" -> Res.drawable.ic_receipt
    "star" -> Res.drawable.ic_star
    "link" -> Res.drawable.ic_link
    "arrow.up.circle" -> Res.drawable.ic_circle_arrow_up
    "arrow.down.circle" -> Res.drawable.ic_circle_arrow_down
    "slider.horizontal.3" -> Res.drawable.ic_sliders_horizontal
    "shippingbox" -> Res.drawable.ic_package
    "checkmark.icloud" -> Res.drawable.ic_cloud_check
    "line.3.horizontal.decrease.circle" -> Res.drawable.ic_list_filter
    else -> null
}
